a={"car","bike","cycle"}
print(len(a))
print(type(a))
a=set(("car","bike","cycle"))
print(a)
for i in a:
    print(i)
print( "bike" in a)
print("cycle" not in a)
print("scooter" in a)
a.add("scooter")
print(a)
b={20,30,50}
a.update (b)
print(a)
a.remove("bike")
print(a)
#a.remove("fan")
print(a)
a.discard("car")
print(a)
a.discard("manu")
print(a)
x=a.pop()
print(x)
print(a)
#a.clear()
print(a)
#del a
c=a.union(b)
print(c)
a=set(("car","bike","cycle"))
d=set(("light","fan","bike"))
e=a.intersection(d)
print(e)
f=a.difference(d)
print(f)
i=a.copy()
print(i)